**12. PyTorch implementation of basic training pipeline**

In [1]:
import numpy as np
import torch as tr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
# dataset: Breast Cancer Detection
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [4]:
# Perform train-test-split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [5]:
# Pre-processing (normalizing)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [6]:
X_train[:3]

array([[-1.53162456, -0.58526681, -1.5101102 , -1.20006996,  0.54158563,
        -0.57039726, -1.10779618, -1.24460716,  0.61570216,  1.15801496,
         0.34114707,  1.50599441,  0.09889236, -0.26939909,  2.85996934,
        -0.3352076 , -1.16831649, -1.91502926, -0.23082356,  1.18586065,
        -1.26317537, -0.47854999, -1.28633808, -0.99300531,  0.61830941,
        -0.7844057 , -1.31170838, -1.72805504, -0.74418186,  0.29979283],
       [-0.30486644, -0.92803473, -0.30181412, -0.35597852, -0.16442469,
        -0.37497807,  0.03324618, -0.36659493,  0.03021197, -0.09270784,
        -0.48966827, -0.75607492, -0.52229097, -0.39258996,  0.50636358,
        -0.30695074, -0.05265181, -0.36843762,  0.83484518, -0.11068459,
        -0.33363814, -0.85166232, -0.30971074, -0.37835969,  0.6968827 ,
        -0.18382758,  0.13936105, -0.26425511,  1.57525266,  0.1671786 ],
       [ 0.17016897,  0.8703543 ,  0.30514953,  0.01119848,  0.57667561,
         1.68916002,  0.97586774,  0.99340391, -0

In [7]:
y_train.head(3)

391    B
154    B
194    M
Name: diagnosis, dtype: object

In [8]:
# label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)
y_train[:5],y_test[:5]

(array([0, 0, 1, 0, 0]), array([0, 1, 1, 0, 1]))

**Main modelling**

In [9]:
# convert to PyTorch tensors
X_train_tensor = tr.from_numpy(X_train)
X_test_tensor = tr.from_numpy(X_test)

y_train_tensor = tr.from_numpy(y_train)
y_test_tensor = tr.from_numpy(y_test)

In [10]:
X_train_tensor.shape,y_train_tensor.shape

(torch.Size([455, 30]), torch.Size([455]))

In [11]:
# defining random seed 
random_seed = 14
tr.manual_seed(random_seed)

# defining the model

class myNN():
    def __init__(self,input_size):
        self.weights = tr.rand(input_size,1,dtype=tr.float64,requires_grad=True) # (input-features,1)
        self.bias = tr.zeros(1,dtype=tr.float64,requires_grad=True) 

    def forward(self,x):
        z = tr.matmul(x,self.weights)+self.bias
        y_pred = tr.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        # clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = tr.clamp(y_pred, epsilon, 1-epsilon) # converts into probability between 0 and 1

        # calculate loss
        loss = -(y*tr.log2(y_pred)+(1-y)*tr.log2((1-y_pred))).mean()
        return loss

In [12]:
# important parameter of Neural Network
learning_rate = 0.1
epochs = 100

**Notes:**
* `.item()` returns the scalar value as a python datatype if tensor is scalar

In [13]:
# training pipeline

### creating model
model = myNN(X_train_tensor.shape[1])
print(model.weights)
# model.weights,model.bias


tensor([[0.5560],
        [0.4420],
        [0.6359],
        [0.4802],
        [0.3392],
        [0.1725],
        [0.8630],
        [0.8465],
        [0.2815],
        [0.1301],
        [0.6738],
        [0.9375],
        [0.6444],
        [0.0295],
        [0.6163],
        [0.1297],
        [0.8779],
        [0.4532],
        [0.9540],
        [0.9087],
        [0.7829],
        [0.5077],
        [0.5884],
        [0.6070],
        [0.1744],
        [0.5493],
        [0.9579],
        [0.5361],
        [0.7519],
        [0.5850]], dtype=torch.float64, requires_grad=True)


In [14]:
### model training

# Loop no of epochs:
for epochi in range(epochs):
    # 1. Forward pass
    y_pred = model.forward(X_train_tensor)

    # 2. Loss Calculation
    loss = model.loss_function(y_pred,y_train_tensor)

    # 3. Backward pass
    loss.backward()

    # 4. Update parameters (don't track gradients while parameters update)
    with tr.no_grad():
        # model.weights -= learning_rate*model.weights.grad
        # model.bias -= learning_rate*model.bias.grad
        model.weights.sub_(learning_rate*model.weights.grad)
        model.bias.sub_(learning_rate*model.bias.grad)

    # 5. zero gradients (stop accumulation of gradient)
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # 6. printing loss in each epoch
    print(f'Epoch: {epochi+1}, Loss:{loss.item()}')

Epoch: 1, Loss:5.802578787670969
Epoch: 2, Loss:5.563533672494807
Epoch: 3, Loss:5.301495071351439
Epoch: 4, Loss:5.031183112853167
Epoch: 5, Loss:4.75152767211995
Epoch: 6, Loss:4.4540750411797205
Epoch: 7, Loss:4.148779828892461
Epoch: 8, Loss:3.8316930189556744
Epoch: 9, Loss:3.497937226100956
Epoch: 10, Loss:3.1700964681234973
Epoch: 11, Loss:2.834541629132644
Epoch: 12, Loss:2.507946116580831
Epoch: 13, Loss:2.211002186244918
Epoch: 14, Loss:1.93727719971855
Epoch: 15, Loss:1.7096715177416841
Epoch: 16, Loss:1.5332611403660381
Epoch: 17, Loss:1.4077745243770816
Epoch: 18, Loss:1.324892361861471
Epoch: 19, Loss:1.2707513521125628
Epoch: 20, Loss:1.2331491360092637
Epoch: 21, Loss:1.204775552243686
Epoch: 22, Loss:1.18184950843871
Epoch: 23, Loss:1.1624671360750607
Epoch: 24, Loss:1.1456390848250806
Epoch: 25, Loss:1.1308099968204386
Epoch: 26, Loss:1.11763265861803
Epoch: 27, Loss:1.1058643725581225
Epoch: 28, Loss:1.0953194040128273
Epoch: 29, Loss:1.085846652206514
Epoch: 30, Los

In [15]:
model.bias

tensor([-0.4958], dtype=torch.float64, requires_grad=True)

In [16]:
# model evaluation
with tr.no_grad():
    y_pred = model.forward(X_test_tensor)
thresh = 0.5
# y_pred_thresh = [int(y.item()>thresh) for y in y_pred]
y_pred_thresh = [int(y>thresh) for y in y_pred]
y_pred_thresh[:5]

[0, 0, 0, 0, 0]

In [19]:
accuracy = (sum(y_pred_thresh == y_test)/len(y_test))*100
print(f'Accuaracy: {accuracy:.2f} %')

Accuaracy: 59.65 %
